### ISSUE TITLE
`npm run start` fails

### ISSUE THREAD

**Issue by mblomdahl** [carlba/buddybudget#4]
After doing `npm install` and proceeding to next section *Running the App* in README, `npm run start` fail with the following error:

<img width="586" alt="image" src="https://user-images.githubusercontent.com/786326/66330688-2ed6a900-e931-11e9-8551-483d3bc4acb5.png">

**Comment by carlba** [comment]
Fixed by as part of #7.

The frontend needs to be built before starting the backend.
```bash
npm run build
```
