### ISSUE TITLE
After starting the app, a 500 error is returned when accessing localhost:3000

### ISSUE THREAD

**Issue by mblomdahl** [carlba/buddybudget#5]
After circumventing #4 by starting a local Postgres database, `npm run start` spins up some kind of web server. But when trying to access http://localhost:3000/ from the browser (Safari), it returns a `{"statusCode":500,"message":"Internal server error"}` error, with the following console error output:

<img width="622" alt="image" src="https://user-images.githubusercontent.com/786326/66331105-19ae4a00-e932-11e9-9e57-a53db3a3b5d9.png">

**Comment by carlba** [comment]
Fixed by as part of #7.

The frontend needs to be built before starting the backend.
```bash
npm run build
```

**Comment by carlba** [comment]
Fixed by as part of #7.

The frontend needs to be built before starting the backend.
```bash
npm run build
```
